# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['soxl_quant_system.py'],
    pathex=[],
    binaries=[],
    datas=[('data', 'data')],
    hiddenimports=[
        'pandas',
        'numpy',
        'requests',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.styles.fonts',
        'openpyxl.styles.patterns',
        'openpyxl.styles.alignment',
        'datetime',
        'json',
        'math',
        'typing',
        'os',
        'sys',
        'traceback',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'pytz',
        'dateutil',
        'dateutil.parser',
        'dateutil.relativedelta',
        'xlrd',
        'et_xmlfile',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'IPython',
        'jupyter',
        'notebook',
        'sphinx',
        'pytest',
        'setuptools',
        'pip',
        'wheel',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='soxl_quant_system',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='soxl_quant_system',
)
